{% set python_min = "3.10" %}
{% set name = "strands-agents" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/strands_agents-{{ version }}.tar.gz
  sha256: d8a24d30653f8e8b1d7ab93c38e70d57f8ea06961c6203409d41ac2abe9282f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - boto3 >=1.26.0,<2.0.0
    - botocore >=1.29.0,<2.0.0
    - docstring_parser >=0.15,<1.0
    - mcp >=1.8.0,<2.0.0
    - pydantic >=2.0.0,<3.0.0
    - typing_extensions >=4.13.2,<5.0.0
    - watchdog >=6.0.0,<7.0.0
    - opentelemetry-api >=1.30.0,<2.0.0
    - opentelemetry-sdk >=1.30.0,<2.0.0
    - opentelemetry-instrumentation-threading >=0.51b0,<1.00b0
    - anthropic >=0.21.0,<1.0.0
    - commitizen >=4.4.0,<5.0.0
    - hatch >=1.0.0,<2.0.0
    - moto >=5.1.0,<6.0.0
    - mypy >=1.15.0,<2.0.0
    - pre-commit >=3.2.0,<4.2.0
    - pytest >=8.0.0,<9.0.0
    - pytest-asyncio >=0.26.0,<0.27.0
    - pytest-cov >=4.1.0,<5.0.0
    - pytest-xdist >=3.0.0,<4.0.0
    - ruff >=0.4.4,<0.5.0
    - sphinx >=5.0.0,<6.0.0
    - sphinx-rtd-theme >=1.0.0,<2.0.0
    - sphinx-autodoc-typehints >=1.12.0,<2.0.0
    - litellm >=1.72.6,<1.73.0
    - llama-api-client >=0.1.0,<1.0.0
    - mistralai >=1.8.2
    - ollama >=0.4.8,<1.0.0
    - openai >=1.68.0,<2.0.0
    - opentelemetry-exporter-otlp-proto-http >=1.30.0,<2.0.0
    - a2a-sdk[sql] >=0.2.11,<1.0.0
    - uvicorn >=0.34.2,<1.0.0
    - httpx >=0.28.1,<1.0.0
    - fastapi >=0.115.12,<1.0.0
    - starlette >=0.46.2,<1.0.0

test:
  imports:
    - strands
  commands:
    - pip check
    - python -c "from strands import Agent"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/strands-agents
  summary: A model-driven approach to building AI agents in just a few lines of code
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://github.com/strands-agents
  dev_url: https://github.com/strands-agents

extra:
  recipe-maintainers:
    - Unshure
    - athkulk
