{% set python_min = "3.10" %}
{% set name = "strands-agents" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/strands_agents-{{ version }}.tar.gz
  sha256: 6946252f7752e54a885e55960940496ff12a698ce45d6a2c82449a93399d3020

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - boto3 >=1.26.0,<2.0.0
    - botocore >=1.29.0,<2.0.0
    - docstring_parser >=0.15,<1.0
    - mcp >=1.8.0,<2.0.0
    - pydantic >=2.0.0,<3.0.0
    - typing_extensions >=4.13.2,<5.0.0
    - watchdog >=6.0.0,<7.0.0
    - opentelemetry-api >=1.30.0,<2.0.0
    - opentelemetry-sdk >=1.30.0,<2.0.0
    - opentelemetry-instrumentation-threading >=0.51b0,<1.00b0

test:
  imports:
    - strands
  commands:
    - pip check
    - python -c "from strands import Agent"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/strands-agents
  summary: A model-driven approach to building AI agents in just a few lines of code
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://github.com/strands-agents
  dev_url: https://github.com/strands-agents

extra:
  recipe-maintainers:
    - Unshure
    - athkulk
